New macro: Change scene to yards
Jagusti/fvtt-wfrp4e-gmtoolkit pull request #189
Opened 2022-09-29 22:16 UTC by AncAinu

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Translation (updates existing localization strings or adds complete new language file)
- [ ] Release (administrative update for tagged release, eg, changelog, readme, manifest)
- [ ] Maintenance (updates to the repository, dependencies and other non-functional code management)

## Checklist:

- [ ] I have run linting on my code to follow the follow the [style](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/blob/dev/.eslintrc.json) of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new unhandled or unexpected warnings.
- [x] My change requires an update to the [documentation](https://github.com/Jagusti/fvtt-wfrp4e-gmtoolkit/wiki).
- [ ] I can be reached on Discord by my handle: ___

## Related Issue(s) 

Fixes or addresses #issue(s):

## Description

Change scene grid to 2 yards, keeping lighting at scale.

### Motivation and context

Useful for maps created for DnD that have a grid of 5ft, or any other grid size.

### Summary of changes

 

### How has this been tested?

### Development / Testing Environment
- Foundry VTT: v9

### Screen Capture

2022-09-29 22:17 UTC, AncAinu commented
I did it for Foundry V9, might not work on v10 (but I'm sure requires just little change).
I'm happy for you to do, or tell me what to do to make this a viable PR.

2022-10-01 08:23 UTC, Jagusti commented
Thanks for the suggested macro ... I really appreciate you following the macro format I'm using. 

I can see this maybe fitting into a toolbox of canvas macros ... something for me to consider in context of a few others 🤔 Certainly timely for the upcoming Light and Vision release. 

As it stands, this won't work on v10 because of the [data model changes](https://foundryvtt.com/article/v10-data-model/). There are minor amends needed to strip out `data` in the object path and switch `gridDistance` to `grid.distance`.  If you get a chance to do it before me, great. If not, can I ask you to just make sure I can make edits to the contribution. Thanks.

2022-10-01 08:26 UTC, Jagusti requested changes
See https://foundryvtt.com/article/v10-data-model/ for v10 data model changes that this should use

2022-10-01 08:26 UTC, Jagusti commented on scripts/macros/change-scene-to-yards.js
> +const newLights = canvas.scene.data.lights.map(light => {
Should now be `canvas.scene.lights`

2022-10-01 08:26 UTC, Jagusti commented on scripts/macros/change-scene-to-yards.js
> +    "config.bright": light.data.config.bright * scale
Also now `lights.config`

2022-10-01 08:26 UTC, Jagusti commented on scripts/macros/change-scene-to-yards.js
> +const scale = 2 / canvas.scene.data.gridDistance;
Should be `canvas.scene.grid.distance`

2022-10-01 08:42 UTC, Jagusti commented on scripts/macros/change-scene-to-yards.js
> +"gridDistance": 2,
Should be `grid.distance`

2022-10-01 08:42 UTC, Jagusti commented on scripts/macros/change-scene-to-yards.js
> +"gridUnits": "yd"
Should be `grid.units`

2023-03-08 21:20 UTC, AncAinu commented
@Jagusti I made the update for V10, also I did use the script in V10, so I can confirm it works well.

2023-04-25 00:13 UTC, Jagusti approved these changes

2023-04-25 00:32 UTC, merged